fix: failure when helmrepository and the helmrelease are in different namespaces
christianh814/mta pull request #18
Opened 2024-11-20 18:40 UTC by nitishfy

Fixes https://github.com/akuity/mta/issues/16

2024-11-20 20:21 UTC, xavidop approved these changes

2024-11-21 18:56 UTC, christianh814 requested changes

2024-11-21 18:56 UTC, christianh814 commented on cmd/helmrelease.go
> +		if helmReleaseName == "" || helmReleaseNamespace == "" {
This isn't needed. You can do this with cobra using [MarkFlagsRequiredTogether](https://pkg.go.dev/github.com/spf13/cobra@v1.7.0#Command.MarkFlagsRequiredTogether).

2024-11-22 10:25 UTC, nitishfy commented on cmd/helmrelease.go
> +		if helmReleaseName == "" || helmReleaseNamespace == "" {
If we use the _MarkFlagsRequiredTogether_, we'll get an error for command that doesn't require either  of those flags such as `mta scan`.

2024-12-12 19:11 UTC, christianh814 approved these changes

2024-12-12 19:11 UTC, christianh814 commented on cmd/helmrelease.go
> +		if helmReleaseName == "" || helmReleaseNamespace == "" {
I believe you can get around that by just using `helmreleaseCmd.MarkFlagsRequiredTogether()` instead of `rootCmd` (requires testing)

2024-12-12 19:11 UTC, christianh814 commented on cmd/helmrelease.go
> +		if helmReleaseName == "" || helmReleaseNamespace == "" {
In the `init()` seciton of helmrelease.go I added

```
	rootCmd.MarkPersistentFlagRequired("name")
	rootCmd.MarkPersistentFlagRequired("namespace")
```

But in the root.go file I had to change it to a blank default

```
rootCmd.PersistentFlags().String("namespace", "", "Namespace of where the Kustomization or HelmRelease is")
```

Now I'm thinking of what was the problem before? The fact that we were defaulting to `flux-system`?

2024-12-12 19:11 UTC, christianh814 commented on cmd/helmrelease.go
> +		if helmReleaseName == "" || helmReleaseNamespace == "" {
Let's move forward with this and we can refactor it later cc @blakepettersson

2024-12-12 19:11 UTC, merged